version: '3'

services:
  nginx:
    container_name: magento2nginx
    build: ./etc/nginx
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - src-volume:/var/www/html
      - src-composer-cache-volume:/root/.composer/cache
    cap_add:
      - "SYS_PTRACE"
  web:
    container_name: magento2web
    restart: always
    ports:
      - "2222:22"
    build: .
    environment:
      PHP_FPM_USER: magento
      PHP_FPM_GROUP: magento
    volumes:
      - src-volume:/var/www/html
      - src-composer-cache-volume:/root/.composer/cache
    cap_add:
      - "SYS_PTRACE"
  db:
    container_name: magento2db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: magento
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    ports:
      - "3306:3306"
    volumes:
      - "./etc/mysql:/etc/mysql/conf.d"
      - db-volume:/var/lib/mysql
  blackfire:
    image: blackfire/blackfire
    environment:
        - BLACKFIRE_SERVER_ID
        - BLACKFIRE_SERVER_TOKEN
volumes:
  src-volume:
  db-volume:
  src-composer-cache-volume:
